version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/home/root/certs:/etc/root/certs"
      - "/var/run/docker.sock:/tmp/docker.sock"

  web:
    build: .
    command: bundle exec foreman start -p 7000
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    ports:
      - 7000
    environment:
      VIRTUAL_HOST: "wdt_single.colima.io"
      RACK_ENV: production
      RAILS_ENV: production
      VIRTUAL_PORT: 7000
      SECRET_KEY_BASE: 21b053f2494f885928d8e456efb15ef2ab4340ff09b562f56c86bdac44a8b6531e32e0d062edbf59030e1e11112f6ccccdd9f7c8e483838a2ba5ce8529deacd9

  redis:
    image: redis

  postgres:
    image: postgres:9.6.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: elpassowrd
