default: &default
  adapter: postgresql
  host: 127.0.0.1
  encoding: utf8

development:
  <<: *default
  database: wdt_dev
  
production:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: wdt_test
